# -*- coding: utf-8 -*-
"""CalculadoraKalebe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wvZTb3gkE48ar_WNZW_OOecrQbPT4QeJ

#**Projeto Calculadora**

A calculadora está dividida em 8 opções:
* Adição
* Subtração
* Multiplicação
* Divisão
* Potenciação
* Resto de divisão
* Desconto
* Saída

A contas são feitas com 2 números de dois inputs diferentes.
"""

#Entrada da calculadora

nome = input('Qual é o seu nome? ') #Pede o nome do usuário da calculadora
print(f'Olá {nome}!') # Imprime esse nome com a mensagem de Olá


while True:  # While True para o programa rodar até escolher "8 - Sair"

#Menu

    print('\n' + '-'*32) # Repete 32x o '-'
    print('1 - Soma            5 - Potenciação')
    print('2 - Subtração       6 - Resto')
    print('3 - Multiplicação   7 - Desconto')
    print('4 - Divisão         8 - Sair')
    print('-'*32)

    escolha = input('Escolha uma opção: ') # Guarda na váriavel escolha a operação desejada pelo usuário

    # Esolha 8 - sair do loop while
    if escolha == '8':
        print('Saindo... Até logo!')
        break  # Quebra o loop principal e encerra o programa

    # Se a escolha for válida (de 1 a 7)
    if escolha in ['1', '2', '3', '4', '5', '6', '7']:
        try: # try - se o usuário digitar uma letra por acidente, o programa não trava, ele apenas avisa o erro.

            # Pedido dos números
            n1 = float(input('Digite o primeiro valor: '))
            n2 = float(input('Digite o segundo valor (ou desconto): '))

            if escolha == '1':
                print(f'Resultado da Soma: {n1 + n2}') # Operação de soma simples
            elif escolha == '2':
                print(f'Resultado da Subtração: {n1 - n2}') # Operação de subtração simples
            elif escolha == '3':
                print(f'Resultado da Multiplicação: {n1 * n2}') # Operação de multiplicação
            elif escolha == '4':
                if n2 == 0:
                    print("Erro: Divisão por zero!") # Caso o número digitado para o divisor seja 0, avisa o usuário que não dá
                else:
                    print(f'Resultado da Divisão: {n1 / n2}') # Qulauqer numero != 0 faz a divisão
            elif escolha == '5':
                print(f'Resultado da Potência: {n1 ** n2}') # Operação de potenciação
            elif escolha == '6':
                print(f'O Resto é: {n1 % n2}') # Operação de resto de divisção
            elif escolha == '7':
                resultado = n1 - (n1 * (n2 / 100)) # Operação de desconto de valor
                print(f'O valor com {n2}% de desconto é: {resultado}')

            # Pergunta se quer voltar ao menu ou fazer outra conta
            continuar = input('\nDeseja fazer outra operação? (S/N): ').upper() #upper para a letra digitada ser convertida para maiuscula
            if continuar != 'S':
                print("Encerrando...")
                break # Quebra o laço while e encerra o programa

        except ValueError: # Mostra o erro caso o usuário digite letras no local dos números
            print("Erro: Por favor, digite apenas números!")
    else:
        print("Opção inválida! Tente novamente.")